### ISSUE TITLE
Problem Creating Epub File

### ISSUE THREAD

**Issue by Meligy** [addyosmani/backbone-fundamentals#238]
I'm having problem creating Epub files, I'm running in Cygwin on windows, and have PdfLatex (via TeXLive), and used to be able to create epub before, which seemed to stop about a week ago or less.

The error I get when I run `make` is:

```
pandoc.exe: .\http://codebyexample.info/wp-content/uploads/2012/04/Screen-Shot-2012-05-01-at-8.57.51-PM.png: openBinaryFile: invalid argument (Invalid argument)
Makefile:21: recipe for target `epub' failed
make: *** [epub] Error 1
```

**Comment by addyosmani** [comment]
Thanks for reporting the issue. I ran into this earlier and it's down to certain images from a recent chapter being external at present. Once we bring all *.codeexample.info images into the repo and reference them locally this issue should be resolved.

**Comment by Meligy** [comment]
Thanks a lot for your reply.

I'm also getting another issue with PDF, also related to images, but not the same error. Could it be the same issue still?

```
pandoc.exe: Error producing PDF from TeX source.
! Package pdftex.def Error: File `http://codebyexample.info/wp-content/uploads/
2012/03/placeholder.png' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.4195 ...content/uploads/2012/03/placeholder.png}

Makefile:37: recipe for target `pdf' failed
make: *** [pdf] Error 43
```

**Comment by dcmaf** [comment]
+1 on this issue!

I presume that until this is fixed the work-around is to download the images manually and then update the md files to reference the local images?

**Comment by addyosmani** [comment]
@dcmaf That's correct. We just need to bring in the external images into the repo and change the URLs to them. That should fix this issue.

**Comment by addyosmani** [comment]
I've fixed this issue in master and included a new ePub build.
